spring.application.name=keycloackadapter
server.port=8088
eureka.client.serviceUrl.defaultZone= ${EUREKA_SERVER:http://localhost:8761/eureka}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=false
spring.cloud.config.enabled=false

keycloak.base-uri=${KEYCLOACK_SERVER:http://localhost:8091/realms/}
keycloak.authorization-uri=${keycloak.base-uri}Career/protocol/openid-connect/auth
keycloak.user-info-uri=${keycloak.base-uri}Career/protocol/openid-connect/userinfo
keycloak.token-uri=${keycloak.base-uri}Career/protocol/openid-connect/token
keycloak.logout=${keycloak.base-uri}Career/protocol/openid-connect/logout
keycloak.jwk-set-uri=${keycloak.base-uri}Career/protocol/openid-connect/certs
keycloak.certs-id=${KEYCLOACK_REAL_ID:7-OgEx9kBooJWnA3fVHzCHf_Z_Vfi5XIquc_f3rcWqo}

keycloak.client-id=front-angular-billing-app
keycloak.client-secret=qwerty
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

logging.level.root=INFO