spring.application.name=BUSINESSDOMAIN-PERSONSERVICE
spring.config.import=optional:configserver:http://configserver:8888
server.port=0
management.endpoints.web.exposure.include=*

#Añadir path global
#server.servlet.context-path=/api/v1
app.base-url=http://localhost:8080
#SPRING SECURITY
spring.security.person.name=admin
spring.security.person.password=admin
google.api.key=AIzaSyDMrtuq9gs0KuNFIsjz-bRwfPVs73VJ11M

#EUREKA
eureka.client.serviceUrl.defaultZone= ${EUREKA_SERVER:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.healthcheck.enabled=true
eureka.client.fetch-registry=true



#POSTGRES BD
spring.datasource.url=jdbc:postgresql://postgres_db:5432/career
spring.datasource.username=postgres
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true